image: registry.git.chalmers.se/courses/dit638/students/2023-group-16/docker:20.10.5

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_CLI_EXPERIMENTAL: enabled
  CI_BUILDX_ARCHS: "linux/amd64,linux/arm64,linux/arm/v7"
  BUILDX_URL: https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64

services:
  - name: registry.git.chalmers.se/courses/dit638/students/2023-group-16/docker:20.10.5-dind
    alias: docker

stages:
  - build
  - deploy

before_script:
  - mkdir -p ~/.docker/cli-plugins
  - BUILDX_URL="https://github.com/docker/buildx/releases/download/v0.6.3/buildx-v0.6.3.linux-amd64"
  - wget -O ~/.docker/cli-plugins/docker-buildx $BUILDX_URL
  - chmod 755 ~/.docker/cli-plugins/docker-buildx
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - DOCKER_CLI_EXPERIMENTAL=enabled docker buildx create --name platformbuilder --use
  - DOCKER_CLI_EXPERIMENTAL=enabled docker buildx inspect --bootstrap
  - DOCKER_CLI_EXPERIMENTAL=enabled docker buildx ls
  - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}

build-and-test:
  stage: build
  script:
    - DOCKER_CLI_EXPERIMENTAL=enabled docker buildx build --platform $CI_BUILDX_ARCHS -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}" --push .
  except:
    - tags
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    expire_in: 60 days
    when: always

release:
  stage: deploy
  script:
    - DOCKER_CLI_EXPERIMENTAL=enabled docker buildx build --platform $CI_BUILDX_ARCHS -t "$CI_REGISTRY_IMAGE":"$CI_COMMIT_TAG" --push .
  only:
    - /^v(\d+\.)?(\d+\.)?(\d+)$/
  dependencies:
    - build-and-test
